### ISSUE TITLE
init fails : Creating config file failed with config directory error

### ISSUE THREAD

**Issue by tdale-dedipath** [JulioLoayzaM/bsimport#1]
Hello,

Following your instructions the init command files with Creating config file failed with config directory error after entering the information.

Thanks!

**Comment by JulioLoayzaM** [comment]
Hi!

That is a rare issue: `config directory error` happens when `init` cannot create the directory for the config files. What OS are you on?

**Comment by tdale-dedipath** [comment]
Ubuntu 22.04 LTS on WSL2

**Comment by JulioLoayzaM** [comment]
> Ubuntu 22.04 LTS on WSL2
Ok, that is a bit weird to me. When I developped this I was using Ubuntu
18.04 on WSL1. Can you confirm that the `~/.config` directory exists on
your WSL filesystem? If the answer is yes, can you create other
directories inside it?

**Comment by tdale-dedipath** [comment]
After running mkdir ~/.config the init command worked. How awkward is that haha.

**Comment by JulioLoayzaM** [comment]
> After running mkdir ~/.config the init command worked. How awkward is that haha.

Great! It's better when the problem is that simple ;)

I'll be closing the issue then, but can I ask for a favor? It's been a
long time since I used Bookstack or bsimport (almost a year since the
last commit!), could you tell me if it still works? So that I can update
the README accordingly. Thanks!
